# 
# Synthesis run script generated by Vivado
# 

set_msg_config -id {HDL 9-1061} -limit 100000
set_msg_config -id {HDL 9-1654} -limit 100000
create_project -in_memory -part xc7a35tcpg236-1

set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_property webtalk.parent_dir C:/Users/folks/Desktop/Vivado/decoder/decoder.cache/wt [current_project]
set_property parent.project_path C:/Users/folks/Desktop/Vivado/decoder/decoder.xpr [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language Verilog [current_project]
set_property vhdl_version vhdl_2k [current_fileset]
read_verilog -library xil_defaultlib C:/Users/folks/Desktop/Vivado/decoder/decoder.srcs/sources_1/new/decoder.v
read_xdc C:/Users/folks/Desktop/Vivado/decoder/Basys-3-Master.xdc
set_property used_in_implementation false [get_files C:/Users/folks/Desktop/Vivado/decoder/Basys-3-Master.xdc]

synth_design -top decoder -part xc7a35tcpg236-1
write_checkpoint -noxdef decoder.dcp
catch { report_utilization -file decoder_utilization_synth.rpt -pb decoder_utilization_synth.pb }
